# Schema for the configuration files of the Domain Alias module.

domain.alias.*:
  type: mapping
  label: 'Domain alias'
  mapping:
    id:
      type: string
      label: 'Alias identifier'
    uuid:
      type: string
      label: 'UUID'
    domain_machine_name:
      type: string
      label: 'Domain machine_name'
    pattern:
      type: string
      label: 'Pattern'
    redirect:
      type: boolean
      label: 'Redirect'
